
const axios = require('axios');
const cheerio = require('cheerio');
const maitre = require('./maitre');
const fs = require('fs');
const readline = require('readline'); 

async function MaitresRestaurateursListURL(page_number= 1) {
    
	try {
	  console.log(`🕵️‍♀️  browsing ?, page number = ${page_number} source`);
	  const restaurantURL = await maitre.scrapePage(page_number);
	  console.log(restaurantURL);   
	  return restaurantURL;
	} catch (e) {
	
	  return {};
	}
  }
  
 
  
  // for a restaurant from the maitres restaurateurs 
  async function MaitresRestaurateurs(searchLink) {
	  
	try {
	  console.log(`🕵️‍♀️  browsing ${searchLink} source`);
  
	  const restaurant = await maitre.scrapeMaitresRestaurateurs(searchLink);
  
	  console.log(restaurant);   

	  
	  return restaurant;
	} catch (e) {

	  return {};
	}
  }



async function fetchMaitresRestaurateursURLList(){ // fetch and store all url of maitre restaurateurs pages

	var numberOfPage=await maitre.scrapeNumberPage(2);
	console.log(numberOfPage);
	var i,restaurantURL;
	var maitresRestaurateursURLList=[];
	for (i = 1; i <= numberOfPage ; i++) 
	{
		restaurantURL=await MaitresRestaurateursListURL(i); 
		maitresRestaurateursURLList=maitresRestaurateursURLList.concat(restaurantURL);
	}
	console.log(maitresRestaurateursURLList.length);
	

	// export in JSON
	fs.writeFile('./files/MaitresRestaurateursURLList.json', JSON.stringify(maitresRestaurateursURLList), (err) => {
		if (err) throw err;
		console.log('Written');
	});
	}

	async function TESTfetchMaitresRestaurateursInfos(){ 

		// import the url
		let rawdata = fs.readFileSync('./files/MaitresRestaurateursURLList.json');
		let url = JSON.parse(rawdata);
		var i,restaurant;
		var maitresRestaurateursList=[];
		//Now let's fetch all the url one by one
		for (i = 0; i < 2; i++) {
			restaurant=await MaitresRestaurateurs(url[i]); 
			  maitresRestaurateursList.push(restaurant);	
		}
	
	
		// export in JSON
		fs.writeFile('./files/MaitresRestaurateurs.json', JSON.stringify(maitresRestaurateursList), (err) => {
			if (err) throw err;
			console.log('Written');
		});
	
	}
async function fetchMaitresRestaurateursInfos(){ //fetch all the restaurants one by one using the json file generated by fetchMaitresRestaurateursURLList()

	// import the url
	let rawdata = fs.readFileSync('./files/MaitresRestaurateursURLList.json');
	let url = JSON.parse(rawdata);
	var i,restaurant;
	var maitresRestaurateursList=[];
	
	for (i = 0; i < url.length; i++) {
		restaurant=await MaitresRestaurateurs(url[i]); 
  		maitresRestaurateursList.push(restaurant);	
	}


	// export in JSON
	fs.writeFile('./files/MaitresRestaurateurs.json', JSON.stringify(maitresRestaurateursList), (err) => {
	    if (err) throw err;
	    console.log('Written');
	});

}

//fetchMaitresRestaurateursURLList();
fetchMaitresRestaurateursInfos();


